### ISSUE TITLE
Possible decoding error for some channels.

### ISSUE THREAD

**Issue by Mq89** [optimeas/python-osf#5]
Executing the print channel example with

```bash
python print_channel_data.py > print_channel_data.txt
```

yields the attached output. For some channels the decoded date makes no sense as it is far in the future.

| Index | Name                        |
| ----: | ---                         |
| 3     | System.Device.Name          |
| 5     | System.Device.BSP           |
| 9     | System.Device.Serial        |
| 27    | System.Device.AppVersion    |
| 31    | System.Device.Version       |
| 33    | System.Device.DeviceManager |
| 41    | System.CPU.ThreadInfo       |
| 48    | System.Device.App           |

```
3: name: System.Device.Name
3: unit: 
3: type: string
3: length: 2

0: ts= 2192-06-19T13:23:57.977671447 | y= smartRAIL-S_Colibri_STH
1: ts= 2192-06-19T13:23:57.977671447 | y= smartRAIL-S_Colibri_STH
```

The underlying int that is converted to this date format is `7020393837977671447` which is already far to large to be in the present.
My guess is, that there is a decoding error from the OSF file.

### Additional observations:
- Most timestamps of the example recording are plausible.
- It is always the data of the entire channel that is off.
- The deviation (if present) is always the same for a channel but differs between channels.
- The deviation is always in the future (except for `System.Config.Version` which seems to be a different problem).
- The channels where it goes wrong have in common that `sizeoflengthvalue="4"`.

[print_channel_data.txt](https://github.com/optimeas/python-osf/files/14650180/print_channel_data.txt)

**Comment by Ezzaldeen97** [comment]
Good observation @Mq89, 

Faced the same issue yesterday.
Also faced it for more signals than the ones you already mentioned
 
| Signal                           |
|--------------------------|
| system.modem.Level    |
| system.hw.BoardVariantInfo |
| system.cfg.Version       |
| system.modem.Network     |
| system.modem.ICCID       |
| system.hw.SoCVariantInfo |

**Comment by Sth79** [comment]
Bugfix is commited, please test it.

**Comment by Mq89** [comment]
It works for me now. 
Thank you!
I think, the issue can be closed.
