### ISSUE TITLE
Value Error while decoding a .osf file

### ISSUE THREAD

**Issue by Kareemaq02** [optimeas/python-osf#7]
The error is caused when the Osf file is decoded in osf4_decode.py. From what I understood is that the error is the result of changing the data type of a NumPy array to a larger one using the view() method, but the size of the new dtype is not compatible with the size of the array's last axis.

![image](https://github.com/optimeas/python-osf/assets/128633276/da217b3a-bffd-4158-bff8-b9bdc4d25a7b)

**Comment by Sth79** [comment]
Can you provide us with a sample file for testing?

**Comment by Kareemaq02** [comment]
Upon investigation, we found that the file 20240219_045522.osfz from truck number 500026 triggered this error. Notably, its size is considerably smaller than usual. Our hypothesis is that a power loss to the data logger during the recording period could have caused this anomaly in file size.

**Comment by Sth79** [comment]
Thanks for the info. I tested the current version of the lib with the osf file "20240219_045522.osfz" from device 500026 and everything worked without any problems. So I will close the issue.
